initramfs-tools-tcos (0.82.9)   * bin/gentcos, hooks-addons/50xorg:     - Add -fix-nvidia-ati option to cache xserver-xorg-core and libgl1-mesa-glx     - Reorganize bin/gentcos with simpler code   * bin/tcos-gdm-autologin:     - Remove wrong licence line (thanks to Quiran to alert me)   * daemonize/daemon.c, daemonize/Makefile:     - Make work daemonize with double fork.
git-svn-id: http://tcosproject.org/svn/tcos/trunk/initramfs-tools-tcos@452 97557d6f-af72-4ac7-98cc-18709f36555f

diff --git a/bin/gentcos b/bin/gentcos
--- a/bin/gentcos
+++ b/bin/gentcos
@@ -4,7 +4,6 @@
 # Author: Mario Izquierdo (a.k.a mariodebian)
 # Email: mariodebian at gmail.com
 # Creation Date: 2 Feb 2006
-# Version: 0.61
 #
 #  Generate bootable cdrom to boot from tcos
 #
@@ -23,6 +22,11 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 ###########################################################################
+
+if [ $UID != 0 ]; then
+ echo "You must run this script as root"
+ exit 1
+fi
 
 . /etc/tcos/tcos.conf
 . ${TCOS_DIR}/tcos-generation-functions.sh
@@ -301,7 +305,8 @@ echo -e "Usage:
           $RED-nbi$NORMAL   [-nbi-output=linux.nbi]   Floppy
           $RED-cdrom$NORMAL [-type=grub] [-force]     CDROM
           $RED-instpkg$NORMAL pkgname
-          $RED-listpkg$NORMAL pkgname
+          $RED-listpkg$NORMAL
+          $RED-fix-nvidia-ati$NORMAL
 
       [-h] or [-help] $(basename $0) extended help
       [${RED}-vmlinux=${WHITE}vmlinuz-x.x.x${RED}|${WHITE}/boot/vmlinuz-x.x.x${NORMAL}] kernel version
@@ -352,6 +357,12 @@ This is gentcos help info about generating net init images.
      ${GREEN}-listpkg${NORMAL}
         This option list all cached packages with -instpkg option
 
+  ${BLUE}Fix NVIDIA/ATI driver problem:${NORMAL}
+     ${GREEN}-fix-nvidia-ati${NORMAL}
+        This option cache xserver-xorg-core and libgl1-mesa-glx 
+        packages to avoid using nvidia/ati libs.
+
+
    In all build you can add this params:
 
     ${BLUE}-vmlinuz${NORMAL}=[ vmlinuz.x.x.x | /boot/vmlinuz.x.x.x ]
@@ -365,6 +376,7 @@ ${WHITE}
      gentcos -nbi -extra-append=\"splash vga=791 uselocal\"
      gentcos -instpkg esound
      gentcos -listpkg
+     gentcos -fix-nvidia-ati
 ${NORMAL}
 "
 }
@@ -374,10 +386,7 @@ if [ $# = 0 ]; then
  _exit 0
 fi
 
-if [ $UID != 0 ]; then
- echo "You must run this script as root"
- _exit 1
-fi
+
 
 alert_need_module() {
        _mod=$1
@@ -395,48 +404,145 @@ alert_need_module() {
       echo "NOTE: You can change kernel version in ${TCOS_CONF}/tcos.conf file"
 }
 
-NEED_MODULES="unionfs|aufs squashfs"
 
-for _module in ${NEED_MODULES}; do
-   have_module=0
-   if [ "$(echo $_module | awk -F "|" '{print $2}')" != "" ]; then
-     for _mod in $(echo $_module | sed 's/|/ /g'); do
-       #_echo "searching for module $_mod"
-       have_one_module=$(modprobe --set-version="${TCOS_KERNEL}" -l ${_mod} | wc -l)
-       if [ ${have_one_module} != 0 ]; then
-          #_echo "have $_mod !!!"
-          have_module=1
+
+check_modules() {
+    NEED_MODULES="unionfs|aufs squashfs"
+
+    for _module in ${NEED_MODULES}; do
+       have_module=0
+       if [ "$(echo $_module | awk -F "|" '{print $2}')" != "" ]; then
+         for _mod in $(echo $_module | sed 's/|/ /g'); do
+           #_echo "searching for module $_mod"
+           have_one_module=$(modprobe --set-version="${TCOS_KERNEL}" -l ${_mod} | wc -l)
+           if [ ${have_one_module} != 0 ]; then
+              #_echo "have $_mod !!!"
+              have_module=1
+           fi
+         done
+       else
+         have_module=$(modprobe --set-version="${TCOS_KERNEL}" -l ${_module} | wc -l)
        fi
-     done
-   else
-     have_module=$(modprobe --set-version="${TCOS_KERNEL}" -l ${_module} | wc -l)
-   fi
 
-   if [ ${have_module} = 0 ] ; then
-      alert_need_module $_module
-      _exit 1
-   fi
-done
+       if [ ${have_module} = 0 ] ; then
+          alert_need_module $_module
+          _exit 1
+       fi
+    done
+}
 
 
+check_xfs() {
+    if [ ! -f /etc/X11/fs/config ]; then
+        echo ""
+        echo "WARNING:"
+        echo "        TCOS needs a font server, please install xfs package"
+        echo "        and configure to allow remote connections. See README."
+        echo ""
+    else
+      xfs_config=$(grep -c "^no-listen" /etc/X11/fs/config)
+      if [ $xfs_config != 0 ]; then
+        echo "WARNING:"
+        echo "        TCOS need a network font server. Please edit /etc/X11/fs/config"
+        echo "        search for no-listen = tcp line and put like this:"
+        echo "                 #no-listen = tcp   "
+        echo "        Then restart service:   /etc/init.d/xfs restart"
+      fi
 
-if [ ! -f /etc/X11/fs/config ]; then
-    echo ""
-    echo "WARNING:"
-    echo "        TCOS needs a font server, please install xfs package"
-    echo "        and configure to allow remote connections. See README."
-    echo ""
-else
-  xfs_config=$(grep -c "^no-listen" /etc/X11/fs/config)
-  if [ $xfs_config != 0 ]; then
-    echo "WARNING:"
-    echo "        TCOS need a network font server. Please edit /etc/X11/fs/config"
-    echo "        search for no-listen = tcp line and put like this:"
-    echo "                 #no-listen = tcp   "
-    echo "        Then restart service:   /etc/init.d/xfs restart"
-  fi
+    fi
+}
 
-fi
+link_vmlinuz() {
+    if [ $TCOS_VMLINUZ ]; then
+       if [ -f $TCOS_VMLINUZ ] ; then
+          vmlinuz=$(basename ${TCOS_VMLINUZ} )
+          TCOS_KERNEL=${vmlinuz#vmlinuz-}
+           if [ $(find  ${TFTP_DIR}/*${vmlinuz}* 2> /dev/null | grep -c vmlinuz) = 0 ]; then
+              # no link, create
+              echo "Linking ${TCOS_VMLINUZ} in ${TFTP_DIR}/"
+              ln -s $TCOS_VMLINUZ ${TFTP_DIR}/
+           fi
+       elif [ -f /boot/${TCOS_VMLINUZ} ]; then
+          vmlinuz=${TCOS_VMLINUZ}
+          TCOS_KERNEL=${vmlinuz#vmlinuz-}
+           if [ $(find  ${TFTP_DIR}/*${vmlinuz}* 2> /dev/null | grep -c vmlinuz) = 0 ]; then
+              # no link, create
+              echo "Linking ${TCOS_VMLINUZ} in ${TFTP_DIR}/"
+              ln -s /boot/$TCOS_VMLINUZ ${TFTP_DIR}/
+           fi      
+       else
+          echo "ERROR: vmlinuz argument not found: ${TCOS_VMLINUZ}"
+          echo "       You can use -vmlinuz=vmlinuz-x.x.x or"
+          echo "                   -vmlinuz=/boot/vmlinuz-x.x.x"
+          echo ""
+          echo "       Using default kernel ${TCOS_KERNEL}"
+       fi
+    fi
+}
+
+
+
+list_pkg() {
+      echo "Installed cached packages are:"
+      ls -1 ${TCOS_PKG_CACHE} 2>/dev/null
+     _exit 0
+}
+
+
+tcos_inst_pkg() {
+  error=0
+  echo "Install PKG \"$1\""
+  for PKG in ${1}; do
+    PKG_URI=$(apt-get install -qq --print-uris --reinstall ${PKG}| egrep 'file|http|ftp' \
+	 | grep "/${PKG}_" | awk '{print $1}'| tr -d "'")
+
+    PKG_PROTOCOL=$(echo ${PKG_URI} | awk -F ":" '{print $1}')
+    if [ "${PKG_PROTOCOL}" = "http" ] || [ "${PKG_PROTOCOL}" = "ftp" ]; then
+      PKG_FILE=/tmp/$(basename $PKG_URI)
+      _echo "  * Downloading ${PKG_URI}"
+      wget -q "${PKG_URI}" -O ${PKG_FILE}
+    elif [ "${PKG_PROTOCOL}" = "file" ]; then
+      PKG_FILE=$(echo ${PKG_URI} | sed s/"file:"//g )
+      echo "Using file:// protocol, package is in ${PKG_FILE} "
+    else
+      echo "Unknow PKG_URI=${PKG_URI} protocol: ${PKG_PROTOCOL} "
+      error=1
+      PKG_FILE=""
+    fi
+    if [ "${PKG_FILE}" = "" ] ; then
+      echo "Error: Unknow package: ${PKG}"
+      error=1
+    else
+      echo "Extracting $(basename ${PKG_FILE})..."
+      rm -rf ${TCOS_PKG_CACHE}/${PKG}
+      mkdir -p ${TCOS_PKG_CACHE}/${PKG}
+      dpkg --extract "${PKG_FILE}" ${TCOS_PKG_CACHE}/${PKG}
+      [ -e /tmp/$(basename $PKG_URI) ] && rm -f /tmp/$(basename $PKG_URI)
+    fi
+  done
+  [ $error = 0 ] && echo "All package installed."
+  [ $error != 0 ] && echo "Ther are some errors during caching..."
+}
+
+
+fix_nvidia_ati() {
+    tcos_inst_pkg "xserver-xorg-core libgl1-mesa-glx"
+    mkdir -p ${TCOS_PKG_CACHE}/fix-nvidia-ati
+    mv ${TCOS_PKG_CACHE}/xserver-xorg-core/usr/lib/xorg/modules/extensions/libglx.so \
+       ${TCOS_PKG_CACHE}/fix-nvidia-ati/libglx.so
+       
+    mv ${TCOS_PKG_CACHE}/xserver-xorg-core/usr/lib/xorg/modules/extensions/libGLcore.so \
+       ${TCOS_PKG_CACHE}/fix-nvidia-ati/libGLcore.so
+       
+    mv ${TCOS_PKG_CACHE}/libgl1-mesa-glx/usr/lib/libGL.so.1.2 \
+       ${TCOS_PKG_CACHE}/fix-nvidia-ati/libGL.so.1.2
+       
+    rm -rf ${TCOS_PKG_CACHE}/xserver-xorg-core
+    rm -rf ${TCOS_PKG_CACHE}/libgl1-mesa-glx
+    echo "NVIDIA/ATI cache done"
+    _exit 0
+}
+
 for opt in $@ ; do
    case ${opt} in
         -h) _help
@@ -492,79 +598,40 @@ for opt in $@ ; do
         -rootfs)
             TCOS_ROOTFS=1
             ;;
-        -instpkg) TCOS_INST_PKG=${@#-instpkg}
+        -instpkg) tcos_inst_pkg "${@#-instpkg}"; _exit 0
             ;;
-        -listpkg) TCOS_LIST_PKG=1
+        -listpkg) list_pkg
+            ;;
+        -fix-nvidia-ati) fix_nvidia_ati
+            ;;
+        --*)
+            echo "Double -- is not accepted as comand line parameter."
+            echo "See $0 -help to know about usage"
+            _exit 1
             ;;
 	esac
 done
 
-if [ "${TCOS_LIST_PKG}" = "1" ]; then
-  echo "Installed cached packages are:"
-  ls -1 ${TCOS_PKG_CACHE} 2>/dev/null
- _exit 0
-fi
 
-if [ "${TCOS_INST_PKG}" != "" ]; then
-  echo "Install PKG \"$TCOS_INST_PKG\""
-  for PKG in ${TCOS_INST_PKG}; do
-    PKG_URI=$(apt-get install -qq --print-uris --reinstall ${PKG}| egrep 'file|http|ftp' \
-	 | grep "/${PKG}_" | awk '{print $1}'| tr -d "'")
 
-    PKG_PROTOCOL=$(echo ${PKG_URI} | awk -F ":" '{print $1}')
-    if [ "${PKG_PROTOCOL}" = "http" ] || [ "${PKG_PROTOCOL}" = "ftp" ]; then
-      PKG_FILE=/tmp/$(basename $PKG_URI)
-      _echo "  * Downloading ${PKG_URI}"
-      wget -q "${PKG_URI}" -O ${PKG_FILE}
-    elif [ "${PKG_PROTOCOL}" = "file" ]; then
-      PKG_FILE=$(echo ${PKG_URI} | sed s/"file:"//g )
-      echo "Using file:// protocol, package is in ${PKG_FILE} "
-    else
-      echo "Unknow PKG_URI=${PKG_URI} protocol: ${PKG_PROTOCOL} "
-      PKG_FILE=""
-    fi
-    if [ "${PKG_FILE}" = "" ] ; then
-      echo "Error: Unknow package: ${PKG}"
-    else
-      echo "Extracting $(basename ${PKG_FILE})..."
-      rm -rf ${TCOS_PKG_CACHE}/${PKG}
-      mkdir -p ${TCOS_PKG_CACHE}/${PKG}
-      dpkg --extract "${PKG_FILE}" ${TCOS_PKG_CACHE}/${PKG}
-      [ -e /tmp/$(basename $PKG_URI) ] && rm -f /tmp/$(basename $PKG_URI)
-    fi
-  done
-  echo "All package installed."
- _exit 0
-fi
+
+
+
+################# START APP here ############################
+
+# link vmlinuz in TFTP_DIR
+link_vmlinuz
+
+# check for unionfs and squashfs
+check_modules
+
+# check for XFS setup
+check_xfs
 
 # make a pxelinux.cfg/default with this kernel
 parse_pxelinuxcfg
 
-if [ $TCOS_VMLINUZ ]; then
-   if [ -f $TCOS_VMLINUZ ] ; then
-      vmlinuz=$(basename ${TCOS_VMLINUZ} )
-      TCOS_KERNEL=${vmlinuz#vmlinuz-}
-       if [ $(find  ${TFTP_DIR}/*${vmlinuz}* 2> /dev/null | grep -c vmlinuz) = 0 ]; then
-          # no link, create
-          echo "Linking ${TCOS_VMLINUZ} in ${TFTP_DIR}/"
-          ln -s $TCOS_VMLINUZ ${TFTP_DIR}/
-       fi
-   elif [ -f /boot/${TCOS_VMLINUZ} ]; then
-      vmlinuz=${TCOS_VMLINUZ}
-      TCOS_KERNEL=${vmlinuz#vmlinuz-}
-       if [ $(find  ${TFTP_DIR}/*${vmlinuz}* 2> /dev/null | grep -c vmlinuz) = 0 ]; then
-          # no link, create
-          echo "Linking ${TCOS_VMLINUZ} in ${TFTP_DIR}/"
-          ln -s /boot/$TCOS_VMLINUZ ${TFTP_DIR}/
-       fi      
-   else
-      echo "ERROR: vmlinuz argument not found: ${TCOS_VMLINUZ}"
-      echo "       You can use -vmlinuz=vmlinuz-x.x.x or"
-      echo "                   -vmlinuz=/boot/vmlinuz-x.x.x"
-      echo ""
-      echo "       Using default kernel ${TCOS_KERNEL}"
-   fi
-fi
+
 
 
 OUTINITRAMFS=initramfs-${TCOS_KERNEL}
